services:
  database:
    image: "postgres:16.0-alpine3.21"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER= ${POSTGRES_USER}
      - POSTGRES_PASSWORD= ${POSTGRES_PASSWORD}
      - POSTGRES_DB= ${POSTGRES_DB}
    ports:
      - ${POSTGRES_LOCAL_PORT}:${POSTGRES_CONTAINER_PORT}
