services:
  database:
    image: "postgres:16-alpine3.21"
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ../.env.development
    ports:
      - 5432:5432
volumes:
  db_data:
