services:
  database:
    container_name: "postgres-dev"
    image: "postgres:16-alpine3.21"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      TYPE_ENVIRONMENT: ${TYPE_ENVIRONMENT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
volumes:
  db_data:
